[workspace]
members = [
    "mysql_mcp",
    "mysql_mcp_http",
    "mysql_mcp_stdio",
]
resolver = "2"

[workspace.dependencies]
anyhow = "1"
rmcp = { version = "1.7", default-features = false }
tokio = { version = "1", default-features = false }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[workspace.package]
edition = "2024"
license = "MIT"
authors = ["Mathieu-Philippe Bourgeois <bourgeois.mat@gmail.com>"]

[profile.release]
opt-level = "z" 
lto = true
strip = true
codegen-units = 1
